spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: F:/log
#  file: F:/log/sell.log
#  level:
#    com.imooc.LoggerTest: debug
wechat:
  mpAppid: wxf11bcc6aabfd584a
  mpAppSecret: 3d534fe3b7b3c68dfa1db7a4b89bf222
  #下面的个人用不到的
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: 1jeHWfABInitQWEIhVkv17BKBbPjv67mLuLuczulPN0

projectUrl:
  wechatMpAuthorize: http://yscsell.mynatapp.cc
  wechatOpenAuthorize: http://yscsell.mynatapp.cc
  sell: http://yscsell.mynatapp.cc

